#!/usr/bin/env bash

export EMSDK_QUIET=1
source /Users/nico/code/libreoffice/emsdk/emsdk_env.sh

SRC=./src
DIST=./dist
MEMORY=32mb
OPTS='-s WASM_BIGINT -s EXPORTED_FUNCTIONS=["_factorial"] --no-entry'

echo "-> build wasm"
emcc -O3 $SRC/renderer/main.c \
	-o $DIST/assets/app.wasm \
	$OPTS

# fin
echo $'\nfin.'
